const extendedCountries = [
  { name: "Albania", continent_id: 1 },
  { name: "Andorra", continent_id: 1 },
  { name: "Armenia", continent_id: 1 },
  { name: "Austria", continent_id: 1 },
  { name: "Azerbaijan", continent_id: 1 },
  { name: "Belarus", continent_id: 1 },
  { name: "Belgium", continent_id: 1 },
  { name: "Bosnia and Herzegovina", continent_id: 1 },
  { name: "Bulgaria", continent_id: 1 },
  { name: "Croatia", continent_id: 1 },
  { name: "Cyprus", continent_id: 1 },
  { name: "Czech Republic", continent_id: 1 },
  { name: "Denmark", continent_id: 1 },
  { name: "Estonia", continent_id: 1 },
  { name: "Finland", continent_id: 1 },
  { name: "France", continent_id: 1 },
  { name: "Georgia", continent_id: 1 },
  { name: "Germany", continent_id: 1 },
  { name: "Greece", continent_id: 1 },
  { name: "Hungary", continent_id: 1 },
  { name: "Iceland", continent_id: 1 },
  { name: "Ireland", continent_id: 1 },
  { name: "Italy", continent_id: 1 },
  { name: "Kazakhstan", continent_id: 1 },
  { name: "Kosovo", continent_id: 1 },
  { name: "Latvia", continent_id: 1 },
  { name: "Liechtenstein", continent_id: 1 },
  { name: "Lithuania", continent_id: 1 },
  { name: "Luxembourg", continent_id: 1 },
  { name: "Malta", continent_id: 1 },
  { name: "Moldova", continent_id: 1 },
  { name: "Monaco", continent_id: 1 },
  { name: "Montenegro", continent_id: 1 },
  { name: "Netherlands", continent_id: 1 },
  { name: "North Macedonia", continent_id: 1 },
  { name: "Norway", continent_id: 1 },
  { name: "Poland", continent_id: 1 },
  { name: "Portugal", continent_id: 1 },
  { name: "Romania", continent_id: 1 },
  { name: "Russia", continent_id: 1 },
  { name: "San Marino", continent_id: 1 },
  { name: "Serbia", continent_id: 1 },
  { name: "Slovakia", continent_id: 1 },
  { name: "Slovenia", continent_id: 1 },
  { name: "Spain", continent_id: 1 },
  { name: "Sweden", continent_id: 1 },
  { name: "Switzerland", continent_id: 1 },
  { name: "Turkey", continent_id: 1 },
  { name: "Ukraine", continent_id: 1 },
  { name: "United Kingdom", continent_id: 1 },
  { name: "Vatican City", continent_id: 1 },

  { name: "Afghanistan", continent_id: 2 },
  { name: "Bahrain", continent_id: 2 },
  { name: "Bangladesh", continent_id: 2 },
  { name: "Bhutan", continent_id: 2 },
  { name: "Brunei", continent_id: 2 },
  { name: "Cambodia", continent_id: 2 },
  { name: "China", continent_id: 2 },
  { name: "India", continent_id: 2 },
  { name: "Indonesia", continent_id: 2 },
  { name: "Iran", continent_id: 2 },
  { name: "Iraq", continent_id: 2 },
  { name: "Israel", continent_id: 2 },
  { name: "Japan", continent_id: 2 },
  { name: "Jordan", continent_id: 2 },
  { name: "Kuwait", continent_id: 2 },
  { name: "Kyrgyzstan", continent_id: 2 },
  { name: "Laos", continent_id: 2 },
  { name: "Lebanon", continent_id: 2 },
  { name: "Malaysia", continent_id: 2 },
  { name: "Maldives", continent_id: 2 },
  { name: "Mongolia", continent_id: 2 },
  { name: "Myanmar", continent_id: 2 },
  { name: "Nepal", continent_id: 2 },
  { name: "North Korea", continent_id: 2 },
  { name: "Oman", continent_id: 2 },
  { name: "Pakistan", continent_id: 2 },
  { name: "Palestine", continent_id: 2 },
  { name: "Philippines", continent_id: 2 },
  { name: "Qatar", continent_id: 2 },
  { name: "Saudi Arabia", continent_id: 2 },
  { name: "Singapore", continent_id: 2 },
  { name: "South Korea", continent_id: 2 },
  { name: "Sri Lanka", continent_id: 2 },
  { name: "Syria", continent_id: 2 },
  { name: "Taiwan", continent_id: 2 },
  { name: "Tajikistan", continent_id: 2 },
  { name: "Thailand", continent_id: 2 },
  { name: "Timor-Leste", continent_id: 2 },
  { name: "Turkmenistan", continent_id: 2 },
  { name: "United Arab Emirates", continent_id: 2 },
  { name: "Uzbekistan", continent_id: 2 },
  { name: "Vietnam", continent_id: 2 },
  { name: "Yemen", continent_id: 2 },

  { name: "United States", continent_id: 3 }
];


