const countryCodes = {
    Afghanistan: "af",
    Albania: "al",
    Andorra: "ad",
    Armenia: "am",
    Austria: "at",
    Azerbaijan: "az",
    Bahrain: "bh",
    Bangladesh: "bd",
    Belarus: "by",
    Belgium: "be",
    Bhutan: "bt",
    "Bosnia and Herzegovina": "ba",
    Brunei: "bn",
    Bulgaria: "bg",
    Cambodia: "kh",
    China: "cn",
    Croatia: "hr",
    Cyprus: "cy",
    "Czech Republic": "cz",
    Denmark: "dk",
    Estonia: "ee",
    Finland: "fi",
    France: "fr",
    Georgia: "ge",
    Germany: "de",
    Greece: "gr",
    Hungary: "hu",
    Iceland: "is",
    India: "in",
    Indonesia: "id",
    Iran: "ir",
    Iraq: "iq",
    Ireland: "ie",
    Israel: "il",
    Italy: "it",
    Japan: "jp",
    Jordan: "jo",
    Kazakhstan: "kz",
    Kosovo: "rs",
    Kuwait: "kw",
    Kyrgyzstan: "kg",
    Latvia: "lv",
    Lebanon: "lb",
    Liechtenstein: "li",
    Lithuania: "lt",
    Luxembourg: "lu",
    Malaysia: "my",
    Maldives: "mv",
    Malta: "mt",
    Moldova: "md",
    Monaco: "mc",
    Mongolia: "mn",
    Montenegro: "me",
    Myanmar: "mm",
    Nepal: "np",
    Netherlands: "nl",
    "North Macedonia": "mk",
    Norway: "no",
    Oman: "om",
    Pakistan: "pk",
    Palestine: "ps",
    Philippines: "ph",
    Poland: "pl",
    Portugal: "pt",
    Qatar: "qa",
    Romania: "ro",
    Russia: "ru",
    "San Marino": "sm",
    "Saudi Arabia": "sa",
    Serbia: "rs",
    Singapore: "sg",
    Slovakia: "sk",
    Slovenia: "si",
    Spain: "es",
    "Sri Lanka": "lk",
    Sweden: "se",
    Switzerland: "ch",
    Syria: "sy",
    Taiwan: "tw",
    Tajikistan: "tj",
    Thailand: "th",
    "Timor-Leste": "tl",
    Turkey: "tr",
    Turkmenistan: "tm",
    Ukraine: "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United States": "us",
    Uzbekistan: "uz",
    "Vatican City": "va",
    Vietnam: "vn",
    Yemen: "ye",
    Laos: "la",           // added manually
    "South Korea": "kr",  // added manually
    "North Korea": "kp"   // added manually
};

export default countryCodes;
